added damage 2 prof and fixed retrieve

diff --git a/src/microbial_fetcher/retrieveFromMetabit b/src/microbial_fetcher/retrieveFromMetabit
--- a/src/microbial_fetcher/retrieveFromMetabit
+++ b/src/microbial_fetcher/retrieveFromMetabit
@@ -49,6 +49,13 @@ fi
 
 if ! command -v $PYTHONCMD &> /dev/null
 then
+    echo " "$PYTHONCMD" could not be found, trying python3"
+    PYTHONCMD="python3"
+fi
+
+
+if ! command -v $PYTHONCMD &> /dev/null
+then
     echo " "$PYTHONCMD" could not be found, exiting"
     exit;
 fi
